name: Build Windows EXE on version change

on:
  push:
    paths:
      - 'version.txt'  # Trigger only when version.txt is updated
    branches:
      - main

jobs:
  build_windows:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller
          pip install inference

      - name: Build EXE with PyInstaller
        run: pyinstaller main.spec
        shell: bash

      - name: Upload built executable
        uses: actions/upload-artifact@v4
        with:
          name: PiztechSibo-exe
          path: dist/PiztechSibo.exe
          retention-days: 1
